name: 'Install Brief Environment'
description: 'Installs brief version of the project using cache'
inputs:
  node-version:
    description: 'Version of the node environment was cached for'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2

    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Look up node_modules from cache
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: env-${{ hashFiles('bun.lock') }}

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: bun install --frozen-lockfile
      shell: bash
