name: Run Checks
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  setup:
    name: Set up Environment
    uses: ./.github/workflows/cache-environment.yml
    with:
      node-version: ${{ inputs.node-version }}

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Environment
        uses: ./.github/use-environment
        with:
          node-version: ${{ inputs.node-version }}

      - name: Run tests
        run: npm test