name: Run Checks
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  setup:
    uses: ./.github/workflows/cache-environment.yml
    with:
      node-version: ${{ matrix.node-version }}

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Use Environment
        uses: ./.github/workflows/use-environment.yml
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/workflows/use-environment.yml
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: npm test