name: Main CI
on: [push]

jobs:
  lint:
    name: Run Lint Check
    uses: ./.github/workflows/lint.yml

  check:
    needs: lint
    name: Run checks for Node version ${{ matrix.node-version }}
    strategy:
      matrix:
        node-version: [ '22.x', '24.x' ]

    uses: ./.github/workflows/check.yml
    with:
      node-version: ${{ matrix.node-version }}
