name: Main CI
on: [push]

jobs:
  lint:
    name: Run Lint Check
    uses: ./.github/workflows/lint.yml

# it just looks nicer on the graph when you don't use matrix
  check:
    needs: lint
    name: Run checks for Node version ${{ matrix.node-version }}
    strategy:
      matrix:
        node-version: [ '18.x', '20.x', '22.x' ]

    uses: ./.github/workflows/check.yml
    with:
      node-version: ${{ matrix.node-version }}